//01. Query Selectors: Just as we grab elements in CSS using simple chains, we can do the same in JS with them.
    //a) document.querySelectorAll(".className p"); //returns an array-like...
    //b) document.querySelector(".className p"); //returns the first element that matches...
        //NOTE: These methods are also available on all the elements, not just on the 'document'.